import 'package:flutter/material.dart';

// const primary = Color(0xFF007dff);
const primary = Color.fromARGB(255, 255, 255, 255);
const mainColor = Color(0x802FB484);
const secondary = Color(0xFFe54140);
const greyyy = Color(0xFFE0E0E0);
const appBgColor = Color(0xFFbdc0f7);
const appBgColorPrimary = Color.fromARGB(255, 122, 124, 241);
const appBgColorSecondary = Color.fromARGB(255, 255, 82, 82);
const appBgColorTernary = Colors.yellow;
const loginPrimary = Colors.black;
const loginSecondary = Colors.green;
const bottomBarBgColor = Color(0xFFEEEEEE);
const inActiveIcon = Color(0xFFABBEEC);
const upColor = Color(0xFF4bc46d);
const downColor = Colors.red;
const stayColor = Colors.black87;
const shadowColor = Colors.black87;
const bottomBarColor = Color(0xFFF8FCFD);
const glassColor = Color(0xFFEEEEEE);
