name: kiit_connect
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  file_picker: ^8.0.0+1
  flutter_neumorphic: ^3.2.0
  http: ^1.1.0
  path_provider: ^2.1.0
  easy_pdf_viewer: ^1.0.7
  icons_launcher: ^2.0.4
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  inkblob_navigation_bar: ^0.1.2
  fluentui_system_icons: ^1.1.232
  liquid_swipe: ^3.1.0
  timelines: ^0.1.0
  fl_chart: ^0.66.2
  flutter_spinkit: ^5.2.0
  awesome_snackbar_content: ^0.1.3
  flutter_svg: ^2.0.10+1
  flutter_lints: ^3.0.1
  lottie: ^3.1.0
  firebase_storage: ^11.2.4
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_core: ^2.14.0
  flutter_gif: ^0.0.4
  video_player: ^2.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.5
  image: ^4.1.3
  url_launcher: ^6.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Group 14.png"

flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - assets/images/backgrounds/
      - assets/images/splash/
